import type {
  Agent,
  Client,
  MetricCard,
  Payment,
  RevenuePoint,
  Transaction,
} from "@/types";

export const metricCards: MetricCard[] = [
  {
    id: "revenue",
    label: "This month's revenue (Aug)",
    value: "$15,000",
    caption: "Based on 300 active clients",
    trend: "+12% vs last month",
    tone: "brand",
  },
  {
    id: "pending",
    label: "Pending payments",
    value: "$1000",
    caption: "127 clients unpaid",
    tone: "danger",
  },
  {
    id: "clients",
    label: "Total clients",
    value: "$1000",
    caption: "+12% vs last month",
    tone: "default",
  },
  {
    id: "agents",
    label: "Total agents",
    value: "$1000",
    caption: "All agents active today",
    tone: "default",
  },
];

export const revenueSeries: RevenuePoint[] = [
  { month: "Jan", value: 62, fill: "var(--color-brand-dark)" },
  { month: "Feb", value: 38, fill: "var(--color-warning)" },
  { month: "March", value: 70, fill: "var(--color-brand-dark)" },
  { month: "April", value: 57, fill: "var(--color-brand-dark)" },
  { month: "May", value: 74, fill: "var(--color-brand)" },
  { month: "Sat", value: 16, fill: "var(--color-danger)" },
];

export const topAgents = [
  { id: "amara", name: "Amara Osei", amount: "$20" },
  { id: "daniel", name: "Daniel Mensa", amount: "$20" },
  { id: "joana", name: "Joana Dueo", amount: "$20" },
  { id: "lina", name: "Lina Kabila", amount: "$20" },
  { id: "sifa", name: "Sifa Mutombo", amount: "$20" },
  { id: "fidel", name: "Fidel Bosco", amount: "$20" },
  { id: "grace", name: "Grace Uwase", amount: "$20" },
  { id: "ange", name: "Ange Umutoni", amount: "$20" },
  { id: "elyse", name: "Elyse Kamanzi", amount: "$20" },
  { id: "patrick", name: "Patrick Ndayisaba", amount: "$20" },
];

export const transactions: Transaction[] = [
  {
    id: "trx-1",
    date: "12-04-2026",
    clientName: "Amara Osei",
    agentName: "Daniel Mensa",
    billingCycle: "April 2026",
    amount: "$500",
    status: "Paid",
  },
  {
    id: "trx-2",
    date: "12-04-2026",
    clientName: "Anita Mutesi",
    agentName: "Johna Dueo",
    billingCycle: "April 2026",
    amount: "$500",
    status: "Paid",
  },
  {
    id: "trx-3",
    date: "12-04-2026",
    clientName: "Samuel K",
    agentName: "Grace Uwase",
    billingCycle: "April 2026",
    amount: "$500",
    status: "Overdue",
  },
  {
    id: "trx-4",
    date: "12-04-2026",
    clientName: "Irene K",
    agentName: "Patrick Ndayisaba",
    billingCycle: "April 2026",
    amount: "$500",
    status: "Paid",
  },
  {
    id: "trx-5",
    date: "12-04-2026",
    clientName: "Aimee K",
    agentName: "Lina Kabila",
    billingCycle: "April 2026",
    amount: "$500",
    status: "Paid",
  },
  {
    id: "trx-6",
    date: "12-04-2026",
    clientName: "Ariane M",
    agentName: "Daniel Mensa",
    billingCycle: "April 2026",
    amount: "$500",
    status: "Overdue",
  },
];

export const clients: Client[] = [
  {
    id: "amara-osei",
    name: "Amara Osei",
    phone: "07940899789",
    address: "Congo Brazaville",
    registeredDate: "12-04-2026",
    status: "Active",
    subscription: "$20",
  },
  {
    id: "anita-mutesi",
    name: "Anita Mutesi",
    phone: "07940899780",
    address: "Kigali Heights",
    registeredDate: "10-04-2026",
    status: "Active",
    subscription: "$20",
  },
  {
    id: "grace-irakoze",
    name: "Grace Irakoze",
    phone: "07940899781",
    address: "Remera",
    registeredDate: "09-04-2026",
    status: "Inactive",
    subscription: "$20",
  },
  {
    id: "samuel-baku",
    name: "Samuel Baku",
    phone: "07940899782",
    address: "Kimihurura",
    registeredDate: "08-04-2026",
    status: "Active",
    subscription: "$20",
  },
  {
    id: "lina-bosco",
    name: "Lina Bosco",
    phone: "07940899783",
    address: "Musanze",
    registeredDate: "07-04-2026",
    status: "Active",
    subscription: "$20",
  },
  {
    id: "ange-uwera",
    name: "Ange Uwera",
    phone: "07940899784",
    address: "Rubavu",
    registeredDate: "06-04-2026",
    status: "Inactive",
    subscription: "$20",
  },
  {
    id: "elyse-kamanzi",
    name: "Elyse Kamanzi",
    phone: "07940899785",
    address: "Kacyiru",
    registeredDate: "05-04-2026",
    status: "Active",
    subscription: "$20",
  },
  {
    id: "patrick-bahizi",
    name: "Patrick Bahizi",
    phone: "07940899786",
    address: "Nyamirambo",
    registeredDate: "04-04-2026",
    status: "Active",
    subscription: "$20",
  },
  {
    id: "denise-tuyisenge",
    name: "Denise Tuyisenge",
    phone: "07940899787",
    address: "Muhima",
    registeredDate: "03-04-2026",
    status: "Active",
    subscription: "$20",
  },
  {
    id: "fidele-ndayisaba",
    name: "Fidele Ndayisaba",
    phone: "07940899788",
    address: "Gikondo",
    registeredDate: "02-04-2026",
    status: "Inactive",
    subscription: "$20",
  },
];

export const agents: Agent[] = [
  {
    id: "joana-dueo",
    name: "Joana Dueo",
    phone: "07940899789",
    registeredDate: "12-04-2026",
    status: "Active",
    performance: "$50",
    clientsServed: 144,
    region: "Kigali",
  },
  {
    id: "daniel-mensa",
    name: "Daniel Mensa",
    phone: "07940899790",
    registeredDate: "11-04-2026",
    status: "Active",
    performance: "$50",
    clientsServed: 132,
    region: "Gasabo",
  },
  {
    id: "lina-kabila",
    name: "Lina Kabila",
    phone: "07940899791",
    registeredDate: "10-04-2026",
    status: "Inactive",
    performance: "$50",
    clientsServed: 97,
    region: "Kicukiro",
  },
  {
    id: "ange-umutoni",
    name: "Ange Umutoni",
    phone: "07940899792",
    registeredDate: "09-04-2026",
    status: "Active",
    performance: "$50",
    clientsServed: 121,
    region: "Nyarugenge",
  },
  {
    id: "patrick-ndayisaba",
    name: "Patrick Ndayisaba",
    phone: "07940899793",
    registeredDate: "08-04-2026",
    status: "Active",
    performance: "$50",
    clientsServed: 111,
    region: "Musanze",
  },
  {
    id: "grace-uwase",
    name: "Grace Uwase",
    phone: "07940899794",
    registeredDate: "07-04-2026",
    status: "Inactive",
    performance: "$50",
    clientsServed: 84,
    region: "Huye",
  },
  {
    id: "sifa-mutombo",
    name: "Sifa Mutombo",
    phone: "07940899795",
    registeredDate: "06-04-2026",
    status: "Active",
    performance: "$50",
    clientsServed: 119,
    region: "Rubavu",
  },
  {
    id: "fidel-bosco",
    name: "Fidel Bosco",
    phone: "07940899796",
    registeredDate: "05-04-2026",
    status: "Active",
    performance: "$50",
    clientsServed: 103,
    region: "Rusizi",
  },
];

export const payments: Payment[] = [
  {
    id: "payment-1",
    clientId: "amara-osei",
    clientName: "Amara Osei",
    agentId: "joana-dueo",
    agentName: "Joana Dueo",
    months: "1",
    billingMonth: "August 2026",
    receiptNumber: "12345",
    date: "12-04-2026",
    amount: "$50",
    status: "Overdue",
  },
  {
    id: "payment-2",
    clientId: "amara-osei",
    clientName: "Amara Osei",
    agentId: "joana-dueo",
    agentName: "Joana Dueo",
    months: "1",
    billingMonth: "July 2026",
    receiptNumber: "12346",
    date: "10-04-2026",
    amount: "$50",
    status: "Overdue",
  },
  {
    id: "payment-11",
    clientId: "amara-osei",
    clientName: "Amara Osei",
    agentId: "joana-dueo",
    agentName: "Joana Dueo",
    months: "1",
    billingMonth: "June 2026",
    receiptNumber: "12347",
    date: "28-03-2026",
    amount: "$50",
    status: "Paid",
  },
  {
    id: "payment-12",
    clientId: "amara-osei",
    clientName: "Amara Osei",
    agentId: "joana-dueo",
    agentName: "Joana Dueo",
    months: "1",
    billingMonth: "May 2026",
    receiptNumber: "12348",
    date: "26-02-2026",
    amount: "$50",
    status: "Paid",
  },
  {
    id: "payment-13",
    clientId: "amara-osei",
    clientName: "Amara Osei",
    agentId: "joana-dueo",
    agentName: "Joana Dueo",
    months: "1",
    billingMonth: "April 2026",
    receiptNumber: "12349",
    date: "24-01-2026",
    amount: "$50",
    status: "Paid",
  },
  {
    id: "payment-14",
    clientId: "amara-osei",
    clientName: "Amara Osei",
    agentId: "joana-dueo",
    agentName: "Joana Dueo",
    months: "1",
    billingMonth: "March 2026",
    receiptNumber: "12350",
    date: "22-12-2025",
    amount: "$50",
    status: "Paid",
  },
  {
    id: "payment-15",
    clientId: "amara-osei",
    clientName: "Amara Osei",
    agentId: "joana-dueo",
    agentName: "Joana Dueo",
    months: "1",
    billingMonth: "February 2026",
    receiptNumber: "12351",
    date: "20-11-2025",
    amount: "$50",
    status: "Paid",
  },
  {
    id: "payment-16",
    clientId: "amara-osei",
    clientName: "Amara Osei",
    agentId: "joana-dueo",
    agentName: "Joana Dueo",
    months: "1",
    billingMonth: "January 2026",
    receiptNumber: "12352",
    date: "18-10-2025",
    amount: "$50",
    status: "Paid",
  },
  {
    id: "payment-3",
    clientId: "anita-mutesi",
    clientName: "Anita Mutesi",
    agentId: "daniel-mensa",
    agentName: "Daniel Mensa",
    months: "1",
    billingMonth: "April 2026",
    receiptNumber: "12353",
    date: "08-04-2026",
    amount: "$50",
    status: "Paid",
  },
  {
    id: "payment-4",
    clientId: "samuel-baku",
    clientName: "Samuel Baku",
    agentId: "lina-kabila",
    agentName: "Lina Kabila",
    months: "1",
    billingMonth: "April 2026",
    receiptNumber: "12354",
    date: "05-04-2026",
    amount: "$50",
    status: "Paid",
  },
  {
    id: "payment-5",
    clientId: "grace-irakoze",
    clientName: "Grace Irakoze",
    agentId: "ange-umutoni",
    agentName: "Ange Umutoni",
    months: "1",
    billingMonth: "April 2026",
    receiptNumber: "12355",
    date: "04-04-2026",
    amount: "$50",
    status: "Paid",
  },
  {
    id: "payment-6",
    clientId: "lina-bosco",
    clientName: "Lina Bosco",
    agentId: "patrick-ndayisaba",
    agentName: "Patrick Ndayisaba",
    months: "1",
    billingMonth: "April 2026",
    receiptNumber: "12356",
    date: "03-04-2026",
    amount: "$50",
    status: "Paid",
  },
  {
    id: "payment-7",
    clientId: "ange-uwera",
    clientName: "Ange Uwera",
    agentId: "grace-uwase",
    agentName: "Grace Uwase",
    months: "1",
    billingMonth: "April 2026",
    receiptNumber: "12357",
    date: "02-04-2026",
    amount: "$50",
    status: "Overdue",
  },
  {
    id: "payment-8",
    clientId: "elyse-kamanzi",
    clientName: "Elyse Kamanzi",
    agentId: "sifa-mutombo",
    agentName: "Sifa Mutombo",
    months: "1",
    billingMonth: "April 2026",
    receiptNumber: "12358",
    date: "01-04-2026",
    amount: "$50",
    status: "Paid",
  },
  {
    id: "payment-9",
    clientId: "patrick-bahizi",
    clientName: "Patrick Bahizi",
    agentId: "fidel-bosco",
    agentName: "Fidel Bosco",
    months: "1",
    billingMonth: "March 2026",
    receiptNumber: "12359",
    date: "31-03-2026",
    amount: "$50",
    status: "Paid",
  },
  {
    id: "payment-10",
    clientId: "denise-tuyisenge",
    clientName: "Denise Tuyisenge",
    agentId: "daniel-mensa",
    agentName: "Daniel Mensa",
    months: "1",
    billingMonth: "March 2026",
    receiptNumber: "12360",
    date: "30-03-2026",
    amount: "$50",
    status: "Overdue",
  },
  {
    id: "payment-17",
    clientId: "anita-mutesi",
    clientName: "Anita Mutesi",
    agentId: "joana-dueo",
    agentName: "Joana Dueo",
    months: "1",
    billingMonth: "March 2026",
    receiptNumber: "12361",
    date: "29-03-2026",
    amount: "$50",
    status: "Paid",
  },
  {
    id: "payment-18",
    clientId: "samuel-baku",
    clientName: "Samuel Baku",
    agentId: "joana-dueo",
    agentName: "Joana Dueo",
    months: "1",
    billingMonth: "March 2026",
    receiptNumber: "12362",
    date: "27-03-2026",
    amount: "$50",
    status: "Paid",
  },
  {
    id: "payment-19",
    clientId: "grace-irakoze",
    clientName: "Grace Irakoze",
    agentId: "joana-dueo",
    agentName: "Joana Dueo",
    months: "1",
    billingMonth: "March 2026",
    receiptNumber: "12363",
    date: "25-03-2026",
    amount: "$50",
    status: "Paid",
  },
  {
    id: "payment-20",
    clientId: "lina-bosco",
    clientName: "Lina Bosco",
    agentId: "joana-dueo",
    agentName: "Joana Dueo",
    months: "1",
    billingMonth: "March 2026",
    receiptNumber: "12364",
    date: "23-03-2026",
    amount: "$50",
    status: "Paid",
  },
  {
    id: "payment-21",
    clientId: "elyse-kamanzi",
    clientName: "Elyse Kamanzi",
    agentId: "joana-dueo",
    agentName: "Joana Dueo",
    months: "1",
    billingMonth: "March 2026",
    receiptNumber: "12365",
    date: "21-03-2026",
    amount: "$50",
    status: "Paid",
  },
];

export function getClientById(clientId: string) {
  return clients.find((client) => client.id === clientId);
}

export function getAgentById(agentId: string) {
  return agents.find((agent) => agent.id === agentId);
}

export function getPaymentsForClient(clientId: string) {
  return payments.filter((payment) => payment.clientId === clientId);
}

export function getPaymentsForAgent(agentId: string) {
  return payments.filter((payment) => payment.agentId === agentId);
}
