"use client";

export const CANONICAL_PERMISSIONS = [
  "admin_users.view",
  "admin_users.create",
  "admin_users.edit",
  "admin_users.delete",
  "roles.view",
  "roles.create",
  "roles.edit",
  "roles.delete",
  "agents.view",
  "agents.create",
  "agents.edit",
  "agents.delete",
  "clients.view",
  "clients.create",
  "clients.edit",
  "clients.delete",
  "service_types.view",
  "service_types.create",
  "service_types.edit",
  "service_types.delete",
  "locations.view",
  "locations.create",
  "locations.edit",
  "locations.delete",
  "commissions.view",
  "commissions.edit",
  "payments.view",
  "payments.edit",
  "dashboard.view",
  "reports.view",
  "reports.create",
  "imports.view",
  "imports.create",
  "billing.edit",
] as const;

export const PERMISSION_RESOURCE_ORDER = [
  "admin_users",
  "roles",
  "dashboard",
  "agents",
  "clients",
  "payments",
  "reports",
  "imports",
  "service_types",
  "locations",
  "commissions",
  "billing",
] as const;

export type CanonicalPermission = (typeof CANONICAL_PERMISSIONS)[number];
